version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./db:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  api:
    container_name: product-api
    build: .
    depends_on:
      - db
    ports:
      - 80:3000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/product_listing?schema=public